### ISSUE TITLE
Error creating template

### ISSUE THREAD

**Issue by BrunoMine** [minetest-mods/intllib#16]
I've run script to create `template.pot` file.
command:
`../../intllib/tools/xgettext.sh caixa_de_area.lua comandos.lua compatibilidade.lua`

returns:
`Generating template...`
`Updating *.po...`
`msgmerge: erro ao abrir "*.po" para leitura: Arquivo ou diretório não encontrado`
`DONE!`

The system message can be translated by: `error opening "*.po" for reading: File or directory not found`

OS: Ubuntu 16

**Comment by kaeza** [comment]
It happens because there are no translations yet. The template is still generated, so that error can be ignored.

I will try to fix it so it doesn't spew errors.

**Comment by kaeza** [comment]
Should be fixed by 5f00db5d953be798f0d49f258c30d657d0d142aa.

If not, please report and I'll reopen.

Thank you for reporting!

**Comment by BrunoMine** [comment]
The problem remains. This time no system message appeared, but no files were created.
`$ ../../intllib/tools/xgettext.sh editor_schems.lua`
`Generating template...`
`DONE!`

**Comment by kaeza** [comment]
Only the template should be generated.

If you want to create a new translation, execute this command in a terminal (this example for Brazilian Portuguese):

```
msginit --locale=pt_BR.UTF-8 -o locale/pt.po -i locale/template.pot
```

Note: You only need to do this once for every language; the script will happily update the catalogs automatically once you create them.

**Comment by BrunoMine** [comment]
I understand, but the template was not created.

**Comment by BrunoMine** [comment]
I discovered the problem. I'm using a different function to translate the strings.
I'm using a global method `modname.S`. I will need to change the syntax of this, but the problem has been solved.

**Comment by BrunoMine** [comment]
I recommend setting up an alert
`No string found`
